// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdVS5hpd8vN-Fzx37duwQnSGFjj021Ow',
    appId: '1:1027866798328:web:81f02f5924ee633da4f30d',
    messagingSenderId: '1027866798328',
    projectId: 'manic-f5bd0',
    authDomain: 'manic-f5bd0.firebaseapp.com',
    storageBucket: 'manic-f5bd0.appspot.com',
    measurementId: 'G-3N4GYKQC3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNecK7tOG79ZH38ic5Ha3Q4Q_hnYYEheg',
    appId: '1:1027866798328:android:413c5504d2d789bca4f30d',
    messagingSenderId: '1027866798328',
    projectId: 'manic-f5bd0',
    storageBucket: 'manic-f5bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdf1UH4ySiunodwMoutmqdrXgIHybHwqA',
    appId: '1:1027866798328:ios:1482b0943f561a2fa4f30d',
    messagingSenderId: '1027866798328',
    projectId: 'manic-f5bd0',
    storageBucket: 'manic-f5bd0.appspot.com',
    iosBundleId: 'com.manic.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdf1UH4ySiunodwMoutmqdrXgIHybHwqA',
    appId: '1:1027866798328:ios:56d9e00fb9c620cba4f30d',
    messagingSenderId: '1027866798328',
    projectId: 'manic-f5bd0',
    storageBucket: 'manic-f5bd0.appspot.com',
    iosBundleId: 'com.manic.app.RunnerTests',
  );
}
